# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
title: vinjo
author: Vinay
tagline: Code, create, and scale — from enterprise systems to experimental tech.
email: vinay01joshi@gmail.com
description: >-
  Here, I share ideas, tools, and methods that help me balance productivity with creativity while keeping control over my digital world. Dive in, get inspired, and feel free to share your thoughts!
baseurl: "/"
url: "https://blog.vinjo.co.in"

# Social links
twitter_username: vinay01joshi
github_username: vinay01joshi
facebook_username: vinay01joshi
mastodon_username: "@vinay01joshi"
reddit_username: vinay01joshi
rss_path: /feed.xml

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Sass configuration for Dart Sass
sass:
  style: compressed
  quiet_deps: true
  load_paths:
    - _sass

# Default layouts for posts and pages
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: "page"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
